#baseURL = "https://acharlot.42.fr/static"
title = "42 final fantasy"
theme = "m10c"
paginate = 8
canonifyURLs = true

[menu]
	[[menu.main]]
		identifier = "home"
		name = "Home"
		url = "/"
		weight = 2

[params]
	author = "Axel Charlot"
	description = "Student 42LeHavre && FF14 addict"
	menu_item_separator = " - "
	[[params.social]]
		icon = "github"
		name = "Github"
		url = "https://github.com/XaelBaseth"
